update BashInit

diff --git a/BashInit b/BashInit
--- a/BashInit
+++ b/BashInit
@@ -14,13 +14,39 @@
 #########################################################################################
 # ---------------------- import lib    -------------------------------------------------#
 #########################################################################################
-# import bsfl lib
-source ~/lib/bash_lib/bsfl
+import_bsfl() {
+    local __ORIGIN_PATH__="$PWD"
+    script_path="${0%/*}"  # remove the script name ,get the path
+    script_path=${script_path/\./$(pwd)} # if path start with . , replace with $PWD
+    cd "${script_path}"
+
+    # -------------------- start get bsfl --------------------
+    if ! [ -f "bsfl" ]; then
+        # down from local
+        wget -q http://192.168.65.56/qinsl0106/bsfl/raw/master/bsfl
+    fi
+    if ! [ -f "bsfl" ]; then
+        # down from gist
+        wget -q https://gist.githubusercontent.com/qinshulei/af2dfb4aec520ab45771/raw/696a9a03540d423285e7658d6b1a7bb63b87fbbb/bsfl
+    fi
+    if ! [ -f "bsfl" ]; then
+        # down from gist
+        echo "can't find bsfl!"
+        exit 1
+    fi
+    # -------------------- end get bsfl --------------------
+
+    # import bsfl lib
+    source ./bsfl
+    cd "$__ORIGIN_PATH__"
+}
+
+import_bsfl
 
 #########################################################################################
 # ---------------------- main function -------------------------------------------------#
 #########################################################################################
-function main() {
+main() {
     cd_to_script_path
     init_params "$@"
     print_params
@@ -33,7 +59,7 @@ function main() {
 #####################################################################################
 #-------------------------------logic function--------------------------------------#
 #####################################################################################
-function show_usage {
+show_usage() {
     cat <<- _EOF_
 
 A init template for bash script
@@ -45,7 +71,7 @@ _EOF_
     exit 1
 }
 
-function init_params() {
+init_params() {
     ## init parameters
     ## constant and deault value
     MESSAGE_ENABLED=no
@@ -67,21 +93,21 @@ function init_params() {
     fi
 }
 
-function init_value_from_env() {
+init_value_from_env() {
     ## base on enviroment , set default items value .
     is_true ITEM_ENABLED   && items[${#items[*]}]=Item
 }
 
-function init_value_from_opts() {
+init_value_from_opts() {
     ## parse command-line options
-    while getopts "hmc:" var
+    while getopts "hmi:" var
     do
         case $var in
             m) MESSAGE_ENABLED=y
                ;;
             h) show_usage
                ;;
-            c)
+            i)
                 if contains ${items[*]} "${OPTARG}";then
                     option_enabled MESSAGE_ENABLED && printf "env has contains this items : %s \n" "${OPTARG}"
                 else
@@ -94,12 +120,12 @@ function init_value_from_opts() {
     target=${1}
 }
 
-function print_params(){
+print_params(){
     option_enabled MESSAGE_ENABLED && printf "selected items : %s\n" "${items[*]}"
     option_enabled MESSAGE_ENABLED && printf "target : %s\n" "${target}"
 }
 
-function do_process(){
+do_process(){
     if contains ${items[*]} "item";then
         option_enabled MESSAGE_ENABLED && printf "========== start process  : %s\n" "item"
         # do something
@@ -109,7 +135,7 @@ function do_process(){
 #####################################################################################
 #----------------------------common function ---------------------------------------#
 #####################################################################################
-function sleep_1_minute_for_check_params() {
+sleep_1_minute_for_check_params() {
     option_enabled MESSAGE_ENABLED && echo "============================================================"
     option_enabled MESSAGE_ENABLED && echo "sleep 1 minute, for check params again"
     sleep 1m
@@ -117,7 +143,7 @@ function sleep_1_minute_for_check_params() {
     option_enabled MESSAGE_ENABLED && echo "============================================================"
 }
 
-function cd_to_script_path() {
+cd_to_script_path() {
     ## Script path
     script_path="${0%/*}"  # remove the script name ,get the path
     script_path=${script_path/\./$(pwd)} # if path start with . , replace with $PWD
